### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by rande** [baptooo/safely-set-inner-html#1]
Hello,

The configuration should not be global as this will create issue with you want multiple configuration (ie, multiple context ...) either you can have a construct method, or a 2nd parameters with the configuration object.

No global configuration please!

**Comment by baptooo** [comment]
Ok right I will ship this, the original idea of global configuration was to prevent doing it each time we need the lib but the user can export a configured instance in his project

**Comment by rande** [comment]
Works as before ;) 

```js
const safelySetInnerHtml = (str, config = config) => generateDom(html2json(str), config);

**Comment by baptooo** [comment]
https://github.com/baptooo/safely-set-inner-html/tree/refactor/config
