### ISSUE TITLE
Doesn't seem to support br element

### ISSUE THREAD

**Issue by spicq-rambobafet** [baptooo/safely-set-inner-html#10]
Hi Baptooo,

I tried to authorize the <br> element, but I got an error :x 
Maybe your lib create an element like this : `<br> <br/>` ?

> Uncaught Error: br is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`.
>     at invariant (main-react.js:10657)

**Comment by baptooo** [comment]
Thanks for your report !

I figured out that empty elements must be created without any content or else it breaks,

```diff
- const br = React.createElement('br', null, '');
+ const br = React.createElement('br', null);
```

It will be shipped soon in this PR https://github.com/baptooo/safely-set-inner-html/pull/12/files#diff-90a8efdf5af0828f812f5fc83a9e55edR69

**Comment by baptooo** [comment]
@Rambobafet shipped in release https://github.com/baptooo/safely-set-inner-html/releases/tag/v0.0.8
